[package]
name = "primitives"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.16.1", features = ["serde"] }
ndarray-rand = "0.15.0"
ndarray-stats = "0.6.0"
rand = "0.9.2"
serde = { version = "1.0.197", features = ["derive", "rc"] }
plotly = "0.12.1"
